feedback/urls.py
from django.conf.urls import *
from feedback.views import leave_feedback, thanks

urlpatterns = patterns('',
    url(r'^$', leave_feedback, name='leave-feedback'),
    url(r'^thanks/$', thanks, name='thanks'),
)

megaholod/urls.py
from django.conf.urls import patterns, include, url
from filebrowser.sites import site
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
import settings
from megaholod import views
from django.views.generic import DetailView
from product.models import Object
from product.views import objs

urlpatterns = patterns(
    '',
    url(r'^$', 'megaholod.views.index', name='index'),
    url(r'^contacts/', include('feedback.urls'), name='contacts'),
    url(r'^about/', views.about, name='about'),
    url(r'^news/', include('news.urls'), name='news'),
    url(r'^product/', include('product.urls'), name='windows'),
    url(r'^news/', include('news.urls'), name='news'),
    url(r'^objects/$', objs, name='objects'),
    url(r'^objects/(?P<pk>\d+)$', DetailView.as_view(model=Object,
        template_name='object_detail.html')),
    url(r'^tech/(?P<templ>[a-zA-Z0-9_-]{0,25})/$', views.flat_page,
        name='templ'),
    # url(r'^megaholod/', include('megaholod.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/filebrowser/', include(site.urls)),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns(
        '',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':
        settings.MEDIA_ROOT}))

news/urls.py
from django.conf.urls import *
from news.views import block_news, news
from news.models import News
from news.views import NewsListView
from django.views.generic import DetailView

urlpatterns = patterns('',
    url(r'^$', NewsListView.as_view(queryset=News.objects.all(), template_name='news_list.html')),
    url(r'^(?P<pk>\d+)$', DetailView.as_view(model=News, template_name='news_detail.html')),
)

feedback/models.py
# -*- coding:utf-8 -*-
from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings

class Feedback(models.Model):
    """
    feedback model, ordering set to time desc
    default table name changed to 'feedbacks'
    """
    class Meta:
        ordering = ['-time']
        db_table = 'feedbacks'
        verbose_name = 'Обратная связь'
        verbose_name_plural = 'фидбэки'

    name   = models.CharField(max_length=100, verbose_name= 'имя')
    email   = models.EmailField(verbose_name= 'почта')
    phone   = models.CharField( max_length=100, verbose_name='телефон')
    message = models.TextField(max_length=500, verbose_name='сообщение')
    time    = models.DateTimeField(auto_now_add=True, verbose_name='время')

    def __unicode__(self):
        return '%s(%s)'%(self.name, self.phone)

    # def get_absolute_url(self):
    #     return reverse('admin:view-feedback', args=[self.id])

product/models.py
# -*- coding: utf-8 -*-
from django.db import models


class Product(models.Model):
    category_type = (
        ('WD', 'Окна'),
        ('HV', 'Пылесосы')
    )

    category = models.CharField(max_length=2, choices=category_type)
    name = models.CharField(max_length=150)
    image = models.ImageField(upload_to='uploads')
    description = models.TextField(max_length=500)
    priority = models.IntegerField(max_length=100, default=0)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['priority', 'category', 'name']
        verbose_name = 'Продукт'
        verbose_name_plural = 'продукты'

    def get_absolute_url(self):
        return '/windows/%i' % self.id


class Object(models.Model):

    name = models.CharField(max_length=100, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='uploads', verbose_name='картинка')
    date = models.DateTimeField(verbose_name='дата')

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['-date']
        verbose_name = 'Объект'
        verbose_name_plural = 'объекты'

    def get_absolute_url(self):
        return '/objects/%i' % self.id

feedback/forms.py
# -*- coding:utf-8 -*-
from django import forms
from feedback.models import Feedback

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback

    def __init__(self, *args, **kwargs):
        super(FeedbackForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'placeholder' : 'Имя:'})
        self.fields['email'].widget.attrs.update({'placeholder' : 'Электронная почта:'})
        self.fields['phone'].widget.attrs.update({'placeholder' : 'Телефон:'})
        self.fields['message'].widget.attrs.update({'placeholder' : 'Сообщение:'})

feedback/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, render_to_response
from django.template import RequestContext
from django.contrib.flatpages.models import FlatPage
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from feedback.forms import FeedbackForm

def leave_feedback(request, template_name='contacts.html'):
    contacts = FlatPage.objects.get(url=request.path)
    form = FeedbackForm(request.POST or None)
    if form.is_valid():
        feedback = form.save(commit=False)
        feedback.save()
        message = "Your feedback was submitted."
        cd = form.cleaned_data
        send_mail(
                '%s(%s)'%(cd['name'], cd['phone']),
                cd['message'],
                cd.get('email', 'noreply@example.com'),
                ['info@belgorodokno.ru'])
        #redirecting back
        return HttpResponseRedirect(request.POST.get('next', request.META.get('HTTP_REFERER', '/')))
        # return render_to_response(template_name, {'next' : request.GET.get('next', '/'), 'feedback_form': FeedbackForm(None), 'mes':message}, context_instance=RequestContext(request))
    return render_to_response(template_name, {'feedback_form': form, 'contacts': contacts}, context_instance=RequestContext(request))

def thanks(request):
    return render(request, 'thanks.html')

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="ROBOTS" content="ALL" />
    <meta name="title" content="Пластиковые окна и встроенные пылесосы в Белгороде" />
    <meta name="description" content="Только у нас окна фирмы Schüco и пылесосы фирмы CycloVac и Vacoflo" />
    <meta name="keywords" content="Пластиковые окна schuco в Белгороде, Schüco, Cyclovac, vacuflo, встроенные пылесосы в Белгороде, schuco белгород, встроенные пылесосы Cyclovac, встроенные пылесосы vacuflo, Cyclovac белгород, vacuflo белгород, ламинация для окон белгород, фурнитура schuco, белгород">
    <link rel="image_src" href="{{MEDIA_URL}}uploads/preview.png" />
    <meta property="og:title" content="Пластиковые окна и встроенные пылесосы в Белгороде"/>
    <meta property="og:description" content="Только у нас окна фирмы Schüco и пылесосы фирмы CycloVac и Vacoflo"/>
    <meta property="og:image" content="{{MEDIA_URL}}uploads/preview.png"/>
    <meta name="google-site-verification" content="brTK5tuopTw7XtyooahA1HrY_cG5vt-HAwVy6iMjFfE" />
    <meta name='yandex-verification' content='5d3e642824c4c081' />
    <meta name='wmail-verification' content='9c824e3e792893b1' />
    <!-- <link href="{{ STATIC_URL }}bootstrap/css/bootstrap-responsive.css" rel="stylesheet"> -->
    <link href="{{ STATIC_URL }}bootstrap/css/styles.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}bootstrap/css/font-awesome.min.css" rel="stylesheet">
    <title>{% block title %}Окна Schuco и пылесосы в Белгороде{% endblock %}</title>    
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->    
    <script>
        $(function() {
            $('.dropdown-toggle').dropdown();
        });
    </script>
    <script src="http://code.jquery.com/jquery-2.0.0.min.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}bootstrap/js/bootstrap.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}bootstrap/js/dropdown.js" type="text/javascript"></script>
    {% block header %}
    {% endblock %}
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-46618845-3', 'belgorodono.ru');
      ga('send', 'pageview');

    </script>
</head>
<body>
    {% include 'header.html' %}
    {% block page %}Empty Page{% endblock %}
    {% include 'footer.html' %}
</body>
</html>

templates/block_objects.html
<h2><a href="/objects/"><span class="color1">НАШИ</span><br>ОБЪЕКТЫ</a></h2>
<div class="row">
{% if objects_list %}
    <ul class="slider blockobject">
        {% for rec in objects_list %}
        <li class="slide">
            <img src="{{ rec.image.url }}" class="obj_img">
            <h3>{{ rec.name }}</h3>
            <p>{{ rec.description|safe|truncatewords_html:15 }}</p>
        </li>
        {% endfor %}
    </ul>
{% endif %}
</div>

templates/feedback.html
<!-- <ul class="messages">
{% for message in messages %}
    <li{% if message.tags %} class="{{message.tags}}"{% endif %}>{{ message }}</li>
{% endfor %}
</ul> -->
<p>{{mes}}</p>
<form id="contact-form" action="" method="post">
    {% csrf_token %}
    <label class="name">
        {{ feedback_form.name }}
        {{ feedback_form.name.errors }}
    </label>                
    <label class="email">
        {{ feedback_form.email }}
        {{ feedback_form.email.errors }}
    </label>
    <label class="phone">
        {{ feedback_form.phone }}
        {{ feedback_form.phone.errors }}
    </label>
    <label class="message">
        {{ feedback_form.message }}
        {{ feedback_form.message.errors }}
    </label>
    <div  class="form_btns">
        <input type="submit" value="Отправить" class="default_button" />
    </div>
</form>

templates/flat_page.html
{% extends 'base.html' %}
{% block page %}
<div class="container">
    <div class="row">
        <div class="col-md-10">
            <h3>{{ flatpage.title }}</h3>

            {{ flatpage.content|safe|escape }}
        </div>
    </div>    
</div>
{% endblock %}

templates/footer.html
<div class="footer bg-gray space-box">
    <div class="content_footer">
        <div class="footer_priv">
            <div class="col-md-1"></div>
            <div class="col-md-11">
                <ul class="soc_icons">
                    <li><a href="http://www.facebook.com/sharer.php?u={{ request.get_host }}"><span class="icon-facebook"></span></a></li>
                    <li><a href="http://twitter.com/home?status={{ request.get_host }}"><span class="icon-twitter"></span></a></li>
                    <li><a href="https://plus.google.com/share?url={{ request.get_host }}"><span class="icon-google-plus"></span></a></li>
                </ul>
                <p><span class="color1" style="margin-left:0px;float:left">ПРИОРИТЕТ</span> &copy; 2014 - Все права защищены</p>
<!-- Rating@Mail.ru counter -->
<script type="text/javascript">//<![CDATA[
var _tmr = _tmr || [];
_tmr.push({id: "2499124", type: "pageView", start: (new Date()).getTime()});
(function (d, w) {
   var ts = d.createElement("script"); ts.type = "text/javascript"; ts.async = true;
   ts.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//top-fwz1.mail.ru/js/code.js";
   var f = function () {var s = d.getElementsByTagName("script")[0]; s.parentNode.insertBefore(ts, s);};
   if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); }
})(document, window);
//]]></script><noscript><div style="position:absolute;left:-10000px;">
<img src="//top-fwz1.mail.ru/counter?id=2499124;js=na" style="border:0;" height="1" width="1" alt="Рейтинг@Mail.ru" />
</div></noscript>
<!-- //Rating@Mail.ru counter -->
<!-- Rating@Mail.ru logo -->
<a href="http://top.mail.ru/jump?from=2499124">
<img src="//top-fwz1.mail.ru/counter?id=2499124;t=351;l=1" 
style="border:0;" height="18" width="88" alt="Рейтинг@Mail.ru" /></a>
<!-- //Rating@Mail.ru logo -->
<!--LiveInternet counter--><script type="text/javascript"><!--
document.write("<a href='http://www.liveinternet.ru/click' "+
"target=_blank><img src='//counter.yadro.ru/hit?t14.5;r"+
escape(document.referrer)+((typeof(screen)=="undefined")?"":
";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?
screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
";"+Math.random()+
"' alt='' title='LiveInternet: показано число просмотров за 24"+
" часа, посетителей за 24 часа и за сегодня' "+
"border='0' width='88' height='31'><\/a>")
//--></script><!--/LiveInternet-->

            </div>
        </div>
    </div>
</div>

templates/furneture.html
{% extends 'base.html' %}
{% block page %}
<div class="container">
    <div class="row">
        {# <div class="col-md-1"></div> #}
        <div class="col-md-2">
            <img style="margin:20px 5px 5px 5px" class="thumbnail obj_img" src="/media/uploads/3.jpg">
            <img style="margin:5px"class="thumbnail obj_img" src="/media/uploads/ручки SCHUCO в стандартном ИСПОЛНЕНИИ.jpg">
            <img style="margin:5px" class="thumbnail obj_img" src="/media/uploads/ручка в стандартном исполнении.jpg">
        </div>
        <div class="col-md-10">
            <h3>{{ flatpage.title }}</h3>

            {{ flatpage.content|safe|escape }}
        </div>
    </div>    
</div>
{% endblock %}

templates/header.html
<div class="navbar navbar-default" >
    <!-- <div class="navbar-inner"> -->
        <div class="container headerlink">
            <div class="row">
                <div class="col-md-3">
                    <div class="header_phone">+7 (4722) 37-58-33</div>
                    <div class="header_phone">+7 (4722) 37-46-80</div>
                </div>
                <div class="col-md-9">
                    <ul class="nav navbar-nav navbar-right ">
                        <li class="pull-left"><a href="/">На главную</a></li>
                        <li class="pull-left"><a href="/about/">О компании</a></li>
                        <li class="pull-left dropdown">
                            <a href="/product/windows/">Продукция</a>
                            <ul class="dropdown-menu pull-right color1" role="menu" aria-labelledby="dropdownMenu">
                                <li><a tabindex="-1" href="/product/windows/">Пластиковые окна</a></li>
                                <li><a tabindex="-1" href="/product/vacs/">Встроенные пылесосы</a></li>
                            </ul>
                        </li>
                        <li class="pull-left"><a href="/objects/">Объекты</a></li>
                        <li class="pull-left"><a href="/contacts/">Контакты</a></li>
                    </ul>
                </div>
            </div>
            <!-- <a href="/" class="brand"><img src="/media/uploads/logo.png" alt="Мегахолод"></a> -->
        </div>
    <!-- </div> -->
</div>

templates/index.html
{% extends "base.html" %}
{% block header %}
<link href="{{ STATIC_URL }}slider/jquery.bxslider.css" rel="stylesheet" />
<script src="{{ STATIC_URL }}slider/jquery.bxslider.min.js" type="text/javascript"></script>
<script>
    $(document).ready(function(){
      $('.slider').bxSlider({
        slideWidth: 250,
        minSlides: 2,
        maxSlides: 3,
        moveSlides: 1,
        infiniteLoop: true, 
        pager: false,
        resposive: true,
        adaptiveHeight: true
      });
    });
</script>
{% endblock %}
{% block page %}
<div class="body">
    <div class="container-fluid jumbo">
        <div id="crsl" class="carousel slide" data-ride="carousel">
            <!-- Wrapper for slides -->
            <div class="carousel-inner jumbo">
                <div class="item active">
                    <img src="{{MEDIA_URL}}uploads/window_cleaning_SCHUCO.jpg" style="width:100%;overflow: hidden;" alt="...">
                    <div class="container">
                        <div class="carousel-caption" style="bottom:-20px;left:30px;">
                            <h1 style="text-align:left;">ПЛАСТИКОВЫЕ ОКНА</h1>
                            <p class="color1" style="text-align:left;font-size:18px">Зеленные технологии для голубой планеты</p>
                        </div>
                    </div>
                </div>
                <div class="item">
                    <img src="{{MEDIA_URL}}uploads/vac.jpg" style="width:100%;" class="no-repeat center top" alt="...">
                    <div class="container">
                        <div class="carousel-caption" style="bottom:-20px;left:30px;">
                            <h1 style="text-align:left;">ВСТРАЕВАЕМЫЕ ПЫЛЕСОСЫ</h1>
                            <p class="color1" style="text-align:left;font-size:18px">Настало время дышать чистым воздухом!</p>
                        </div>
                    </div>
                </div>
            </div>

          <!-- Controls -->
            <a class="left carousel-control" href="#crsl" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#crsl" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
        <!-- hello -->
        <div class="row bg-light tab">
            <div class="col-md-1"></div>
            <div class="col-md-3"><p class="bigtitle color1">Добро пожаловать!<p></div>
            <div class="col-md-7"><p class="txt2">наш главный приоритет- удовольствие наших Клиентов от использования качественных и современных решений для частного строительства!</p></div>
            <!-- <div class="col-md-1"></div> -->
        </div>
        <!-- products -->
        <div class="row bg-gray">
            <div class="col-md-1"></div>
            <div class="col-md-7">
                <h2><span class="color1">НАШИ</span><br>ПРОДУКТЫ</h2>
                <div class="row">
                    <div class="col-md-3"><img src="{{MEDIA_URL}}uploads/thumbnail_small.jpg" class="thumbnail"></div>
                    <div class="col-md-9" style="padding:0;">
                        <h2 style="margin-top:0"><a href="/product/windows/"><span class="color1">Пластиковые</span><br>Окна</a></h2>
                        <p>Наша компания предлагает Вам использовать стеклопакеты с энергосберегающим стеклом ClimaGuard® Solar, которое подарит Вам не только экономию и комфорт, но и придаст привлекательность Вашим окнам!</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3"><img src="{{MEDIA_URL}}uploads/Cyclovac_logo_small.JPG" class="thumbnail"></div>
                    <div class="col-md-9" style="padding:0;">
                        <h2 style="margin-top:0"><a href="/product/vacs/"><span class="color1">Встраевыемые</span><br>пылесосы</a></h2>
                        <p>Недостатков лишены системы центрального пылеудаления (встроенные пылесосы) CycloVac (Канада) и Vacoflo (США), широко применяемые в коттеджах и городских квартирах.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <h2><span class="color1">НАШИ</span><br>ТЕХНОЛОГИИ</h2>
                <ul class="marklist">
                    <li><span class="glyphicon glyphicon-chevron-right tab30r"></span><a href="http://www.energosteklo.ru/">Энергосберегающие стекла</a></li>
                    <li><span class="glyphicon glyphicon-chevron-right tab30r"></span><a href="/tech/lamination/">Ламинация для окон</a></li>
                    <li><span class="glyphicon glyphicon-chevron-right tab30r"></span><a href="/tech/furneture/">Фурнитура для окон</a></li>
                    <li><span class="glyphicon glyphicon-chevron-right tab30r"></span><a href="http://cyclovac.ru/tehnologies/22-hide-a-hose-sistema-sprjach-shlang.html">"Шланг-невидимка"</a></li>
                    <li><span class="glyphicon glyphicon-chevron-right tab30r"></span><a href="http://cyclovac.ru/tehnologies/16-ultra-fresh-antibaterialnaja-propitka-nesmennogo.html">Антибактериальная пропитка</a></li>
                    <li><span class="glyphicon glyphicon-chevron-right tab30r"></span><a href="http://cyclovac.ru/tehnologies/16-ultra-fresh-antibaterialnaja-propitka-nesmennogo.html">Стильные розетки</a></li>
                    <li><span class="glyphicon glyphicon-chevron-right tab30r"></span><a href="/tech/carbon-filter/">Угольный фильтр</a></li>
                    <li><span class="glyphicon glyphicon-chevron-right tab30r"></span><a href="http://cyclovac.ru/tehnologies/15-datasync-polnyjj-kontrol-sistemy.html">Полный контроль системы</a></li>
                </ul>
            </div>
            <div class="col-md-1"></div>
        </div>
        <div class="row bg-light">
            <div class="col-md-1"></div>
            <!-- objects -->            
            <div class="col-md-7">
                {% include 'block_objects.html' %}
            </div>
            <!-- news -->            
            <div class="col-md-4">
                {% include 'block_news.html' %}
            </div>
            <!-- <div class="col-md-1"></div> -->
        </div>
    </div>
</div>
{% endblock %}

templates/news_list.html
{% extends "base.html" %}
{% block page %}
<div class="container">
    <div class="row">
        {% for rec in object_list %}
        <div class="col-md-10">
            <div class="col-md-4 jumbo num_section">
                <span class="date_txt1">{{ rec.time|date:"d" }}</span>
                <span class="date_txt2">{{ rec.time|date:"M" }}</span>
                <span class="date_txt3">{{ rec.time|date:"Y" }}</span>
            </div>
            <h2>{{ rec.title }}</h2>
            <p>{{ rec.text|safe|truncatewords_html:30 }}</p>
            <a href="/news/{{rec.id}}" class="more_btn" >Узнать больше</a>
        </div>
        {% endfor %} 
    </div>
</div>
{% endblock %}

templates/object_detail.html
{% extends "base.html" %}
{% block title %}
{{ object.name}}
{% endblock %}
{% block page %}
<div class="container">
    <div class="row">
    <h3>{{ object.name}}</h3>
    {{ object.description|safe}}
    </div>
</div>
{% endblock %}

templates/product_detail.html
{% extends "base.html" %}
{% block title %}
{{ product.name}}
{% endblock %}
{% block page %}
<div class="container">
    <div class="row">
    <h3>{{ product.name}}</h3>
    {{ product.description|safe}}
    </div>
</div>
{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block page %}
<h2>Thanks</h2>
{% endblock %}

templates/vac_list.html
{% extends "base.html" %}
{% block page %}
<div class="container">
    <div class="row">
        {% for rec1, rec2, rec3 in kort %}
        <div class="col-md-4">
            <div class="box-2">
                <img width="280" height="280" class="thumbnail" src="{{ rec1.image.url }}">
                <h3>{{ rec1.name }}</h3>
                <p>{{ rec1.description|safe|truncatewords_html:15 }}</p>
                <a href="/product/vacs/{{rec1.id}}"  class="more_btn">Узнать больше</a>
            </div>
        </div>
        {% if rec2 %}
        <div class="col-md-4"> 
            <div class="box-2">
                <img width="280" height="280" class="thumbnail" src="{{ rec2.image.url }}">
                <h3>{{ rec2.name }}</h3>
                <p>{{ rec2.description|safe|truncatewords_html:15 }}</p>
                <a href="/product/vacs/{{rec2.id}}"  class="more_btn">Узнать больше</a>
            </div>
        </div>
        {% endif %}
        {% if rec3 %}
        <div class="col-md-4"> 
            <div class="box-2">
                <img width="280" height="280" class="thumbnail" src="{{ rec3.image.url }}">
                <h3>{{ rec3.name }}</h3>
                <p>{{ rec3.description|safe|truncatewords_html:15 }}</p>
                <a href="/product/vacs/{{rec3.id}}" class="more_btn">Узнать больше</a> 
            </div>
        {% endif %}
        </div>
        {% endfor %} 
    </div>
</div>
{% endblock %}

templates/windows_list.html
{% extends "base.html" %}
{% block page %}
<div class="container">
    <div class="row">
        {% for rec1, rec2, rec3 in kort %}
        <div class="col-md-4">
            <div class="box-2">
                <img width="280" height="280" class="thumbnail" src="{{ rec1.image.url }}">
                <h3>{{ rec1.name }}</h3>
                <p>{{ rec1.description|safe|truncatewords_html:15 }}</p>
                <a href="/product/windows/{{rec1.id}}"  class="more_btn">Узнать больше</a>
            </div>
        </div>
        {% if rec2 %}
        <div class="col-md-4"> 
            <div class="box-2">
                <img width="280" height="280" class="thumbnail" src="{{ rec2.image.url }}">
                <h3>{{ rec2.name }}</h3>
                <p>{{ rec2.description|safe|truncatewords_html:15 }}</p>
                <a href="/product/windows/{{rec2.id}}"  class="more_btn">Узнать больше</a>
            </div>
        </div>
        {% endif %}
        {% if rec3 %}
        <div class="col-md-4"> 
            <div class="box-2">
                <img width="280" height="280" class="thumbnail" src="{{ rec3.image.url }}">
                <h3>{{ rec3.name }}</h3>
                <p>{{ rec3.description|safe|truncatewords_html:15 }}</p>
                <a href="/product/windows/{{rec3.id}}" class="more_btn">Узнать больше</a> 
            </div>
        {% endif %}
        </div>
        {% endfor %} 
    </div>
</div>
{% endblock %}